### ISSUE TITLE
1.0 TODO

### ISSUE THREAD

**Issue by dy** [dfcreative/calc-sdf#1]
* [x] make sure name is good
  * since we are dealing with shapes - mb `bitmap-sdf`, `shape-sdf`, `font-sdf`, `canvas-sdf`, `glyph-sdf`, `bw-sdf`? Matlab named this `bwdist`
* [x] figure out input/output arguments - every possible or only 1-channel uint8? Or flexible? Is there standard for image/bw data? It def should not be only canvas to work in node/webworker.
* [x] add demo
* [x] add travis test
